image end_1 = "images/end_game/end_1.png"
image end_2 = "images/end_game/end_2.png"
image end_3 = "images/end_game/end_3.png"
image end_4 = "images/end_game/end_4.png"
image end_5 = "images/end_game/end_5.png"
image end_6 = "images/end_game/end_6.png"
image end_7 = "images/end_game/end_7.png"
image end_8 = "images/end_game/end_8.png"
image end_9 = "images/end_game/end_9.png"
image end_10 = "images/end_game/end_10.png"

image end_pic1 = "images/end_game/komomo_end3.png"
image end_pic2 = "images/end_game/mare_end2.png"
image end_pic3 = "images/end_game/mare_end3.png"
image end_pic4 = "images/end_game/mare_end7.png"
image end_pic5 = "images/end_game/mareyume_end1.png"
image end_pic6 = "images/end_game/mareyume_end3.png"
image end_pic7 = "images/end_game/mareyume_end5.png"

image end_graph = "images/end_game/end_bg.jpg"
image end_graph2 = "images/end_game/end_bg2.jpg"

image end_pic2_1 = "images/end_game/pic2_1.png"
image end_pic2_2 = "images/end_game/pic2_2.png"
image end_pic2_3 = "images/end_game/pic2_3.png"
image end_pic2_4 = "images/end_game/pic2_4.png"
image end_pic2_5 = "images/end_game/pic2_5.png"
image end_pic2_6 = "images/end_game/pic2_6.png"
image end_pic2_7 = "images/end_game/pic2_7.png"

image end2_1 = "images/end_game/end2_1.png"
image end2_2 = "images/end_game/end2_2.png"
image end2_3 = "images/end_game/end2_3.png"
image end2_4 = "images/end_game/end2_4.png"
image end2_5 = "images/end_game/end2_5.png"
image end2_6 = "images/end_game/end2_6.png"
image end2_7 = "images/end_game/end2_7.png"
image end2_8 = "images/end_game/end2_8.png"
image end2_9 = "images/end_game/end2_9.png"
image end2_10 = "images/end_game/end2_10.png"

image fin = "images/end_game/final.png"
image endback1 = "images/end_game/endback1.jpg"
